import Web3 from 'web3';
	const ETHEREUM_CLIENT = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"))	
	var masterstorageABI = [{"constant":false,"inputs":[{"name":"_projectName","type":"string"}],"name":"getCurr","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"},{"name":"_isPublic","type":"bool"}],"name":"init","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"}],"name":"exists","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"}],"name":"getHash","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"}],"name":"remove","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"},{"name":"_projectHash","type":"string"}],"name":"commit","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"},{"name":"_projectOwner","type":"address"}],"name":"guestPull","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"},{"name":"_pastcommit","type":"uint256"}],"name":"getHist","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_projectName","type":"string"}],"name":"ownerPull","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"}]	

var masterAddress = '0x732d8bc69319cb3f8172e755f3ab9a55dff340bc';
const masterContract = ETHEREUM_CLIENT.eth.contract(masterstorageABI).at(masterAddress);
export {masterContract};


